// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
    public partial class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.AddMarkupContent(0, "<h1>Single line statement</h1>\r\n\r\nTime: ");
#nullable restore
#line (3,8)-(3,20) 24 "x:\dir\subdir\Test\TestComponent.cshtml"
__builder.AddContent(1, DateTime.Now);

#line default
#line hidden
#nullable disable
            __builder.AddMarkupContent(2, "\r\n\r\n");
            __builder.AddMarkupContent(3, "<h1>Multiline block statement</h1>\r\n\r\n");
#nullable restore
#line (7,2)-(10,4) 24 "x:\dir\subdir\Test\TestComponent.cshtml"
__builder.AddContent(4, JsonToHtml(@"{
  'key1': 'value1'
  'key2': 'value2'
}"));

#line default
#line hidden
#nullable disable
            __builder.AddMarkupContent(5, "\r\n\r\n");
            __builder.AddMarkupContent(6, "<h1>Component with type args</h1>\r\n");
            __builder.OpenComponent<Test.MyComponent>(7);
            __builder.AddAttribute(8, "IntProperty", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Int32>(
#nullable restore
#line 14 "x:\dir\subdir\Test\TestComponent.cshtml"
                 123

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(9, "BoolProperty", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.Boolean>(
#nullable restore
#line 15 "x:\dir\subdir\Test\TestComponent.cshtml"
                  true

#line default
#line hidden
#nullable disable
            ));
            __builder.AddAttribute(10, "StringProperty", "My string");
            __builder.AddAttribute(11, "ObjectProperty", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Test.SomeType>(
#nullable restore
#line 17 "x:\dir\subdir\Test\TestComponent.cshtml"
                    new SomeType()

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
